In this lesson, you created a middleware function called asyncWrapper. Why?
   To avoid redandancy in code.
   Centralize error handling.


const getTask = asyncWrapper(async (req, res, next) => {  
  const { id: taskID } = req.params;  
  const task = await Task.findOne({ _id: taskID });  
  if (!task) {  
    // your code here  
    return next(createCustomError(`No task with id: ${taskID}`, 404))
  }  
  res.status(200).json({ task });  
}); 